# Generated by Django 5.2.6 on 2026-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
