# Generated by Django 5.2.6 on 2025-12-10 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_date_attendancerecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrsession',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
