# Generated by Django 5.2.6 on 2026-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrsession_created_ip_qrsession_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
